//! Ren'Py translation file adapter (AiNiee RenpyReader equivalent).
//!
//! Operates on the `.rpy` files generated by Ren'Py's `translate` command:
//!
//! ```text
//! translate chinese start_abc123:
//!     # e "こんにちは"
//!     e "こんにちは"          ← replaced with the translation
//!
//! translate chinese strings:
//!     old "セーブ"
//!     new ""                  ← filled with the translation
//! ```
//!
//! Only lines inside `translate` blocks are touched. `{tags}` and `[vars]`
//! must be preserved by the model (enforced in the system prompt).

use super::{FormatAdapter, OutputFile, output_sibling};
use crate::model::{ItemType, TextUnit, Translation, needs_translation};
use anyhow::Result;
use std::collections::BTreeMap;
use std::path::Path;

pub struct RenpyAdapter;

/// Statements whose quoted argument is an asset path, not dialogue.
const NON_TEXT_STMTS: &[&str] = &[
    "voice", "play", "queue", "show", "scene", "image", "jump", "call", "pause", "stop", "window",
    "hide", "with",
];

impl FormatAdapter for RenpyAdapter {
    fn id(&self) -> &'static str {
        "renpy"
    }
    fn label(&self) -> &'static str {
        "Ren'Py translation file"
    }
    fn extensions(&self) -> &'static [&'static str] {
        &["rpy"]
    }

    fn extract(&self, input: &Path, source_lang: &str) -> Result<Vec<TextUnit>> {
        let body = crate::textio::read_text(input)?;
        let mut units = Vec::new();
        let mut in_translate = false;
        let mut pending_old: Option<String> = None;
        for (i, raw) in body.lines().enumerate() {
            let line = raw.trim_end_matches('\r');
            let t = line.trim_start();
            if t.starts_with("translate ") {
                in_translate = true;
                pending_old = None;
                continue;
            }
            if !in_translate || t.is_empty() || t.starts_with('#') {
                continue;
            }
            if let Some(rest) = t.strip_prefix("old ") {
                pending_old = last_quoted(rest).map(|(_, _, s)| s);
                continue;
            }
            if t.starts_with("new ") {
                if let Some(old) = pending_old.take() {
                    push_unit(&mut units, &old, i + 1, source_lang, "strings");
                }
                continue;
            }
            // dialogue line: `e "text"` / `"text"` — the quoted text is the original
            let first_word = t.split_whitespace().next().unwrap_or("");
            if NON_TEXT_STMTS.contains(&first_word) {
                continue;
            }
            if let Some((_, _, text)) = last_quoted(t) {
                push_unit(&mut units, &text, i + 1, source_lang, "dialogue");
            }
        }
        Ok(units)
    }

    fn writeback(
        &self,
        input: &Path,
        target_lang: &str,
        units: &[TextUnit],
        translations: &BTreeMap<String, Translation>,
    ) -> Result<Vec<OutputFile>> {
        let body = crate::textio::read_text(input)?;
        let mut lines: Vec<String> = body
            .lines()
            .map(|l| l.trim_end_matches('\r').to_string())
            .collect();
        for u in units {
            let Some(tr) = translations.get(&u.id) else {
                continue;
            };
            let Ok(lineno) = u.location.trim_start_matches('n').parse::<usize>() else {
                continue;
            };
            let Some(slot) = lines.get_mut(lineno - 1) else {
                continue;
            };
            let Some((start, end, _)) = last_quoted(slot) else {
                continue;
            };
            let escaped = renpy_escape(&tr.translation_lines.join("\n"));
            *slot = format!("{}{}{}", &slot[..start], escaped, &slot[end..]);
        }
        let mut out = lines.join("\n");
        out.push('\n');
        Ok(vec![OutputFile::text(
            output_sibling(input, target_lang, "rpy"),
            out,
        )])
    }
}

fn push_unit(
    units: &mut Vec<TextUnit>,
    text: &str,
    lineno: usize,
    source_lang: &str,
    domain: &str,
) {
    let unescaped = renpy_unescape(text);
    if unescaped.trim().is_empty() || !needs_translation(&unescaped, source_lang) {
        return;
    }
    let lines: Vec<String> = unescaped.split('\n').map(str::to_string).collect();
    let location = format!("n{lineno:06}");
    units.push(TextUnit {
        id: TextUnit::compute_id("renpy", &location, &lines),
        engine: "renpy".into(),
        domain: domain.into(),
        location,
        item_type: ItemType::LongText,
        role: String::new(),
        original_lines: lines,
        source_line_paths: vec![],
        context: format!("s{:04}", lineno / 60),
        payload: String::new(),
    });
}

/// Content byte span (inside the quotes) and unescaped-ish value of the last
/// double-quoted string on the line.
fn last_quoted(line: &str) -> Option<(usize, usize, String)> {
    let bytes = line.as_bytes();
    let mut spans = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'"' {
            let start = i + 1;
            let mut j = start;
            while j < bytes.len() {
                match bytes[j] {
                    b'\\' => j += 2,
                    b'"' => break,
                    _ => j += 1,
                }
            }
            if j <= bytes.len() {
                spans.push((start, j.min(bytes.len())));
                i = j + 1;
                continue;
            }
        }
        i += 1;
    }
    let (start, end) = *spans.last()?;
    let content = line.get(start..end)?.to_string();
    Some((start, end, content))
}

fn renpy_unescape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        if c == '\\' {
            match chars.next() {
                Some('n') => out.push('\n'),
                Some('"') => out.push('"'),
                Some('\'') => out.push('\''),
                Some('\\') => out.push('\\'),
                Some(other) => {
                    out.push('\\');
                    out.push(other);
                }
                None => out.push('\\'),
            }
        } else {
            out.push(c);
        }
    }
    out
}

fn renpy_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renpy_dialogue_and_strings() {
        let dir = super::super::test_dir("renpy");
        let input = dir.join("a.rpy");
        std::fs::write(
            &input,
            r#"# outside "無視される"
translate chinese start_ab12:

    # e "こんにちは"
    e "こんにちは"

translate chinese strings:

    old "セーブ"
    new ""
"#,
        )
        .unwrap();
        let units = RenpyAdapter.extract(&input, "ja").unwrap();
        assert_eq!(units.len(), 2, "{units:#?}");
        let mut tr = BTreeMap::new();
        for (u, text) in units.iter().zip(["你好", "存档"]) {
            tr.insert(
                u.id.clone(),
                Translation {
                    unit_id: u.id.clone(),
                    translation_lines: vec![text.to_string()],
                    source_hash: TextUnit::source_hash(&u.original_lines),
                    passthrough: false,
                },
            );
        }
        let outs = RenpyAdapter.writeback(&input, "zh", &units, &tr).unwrap();
        let body = String::from_utf8(outs[0].bytes.clone()).unwrap();
        assert!(body.contains(r#"e "你好""#), "{body}");
        assert!(body.contains(r#"# e "こんにちは""#), "comment kept: {body}");
        assert!(body.contains(r#"new "存档""#), "{body}");
        assert!(body.contains(r#"old "セーブ""#), "{body}");
        assert!(body.contains(r#"# outside "無視される""#), "{body}");
    }
}
